### ISSUE TITLE
Page not found: https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture/MVC_architecture

### ISSUE THREAD

**Issue by ktapia576** [mdn/sprints#1137]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

I am trying to view this web page, but the page is not found. I linked it to others and they have the same issue. I posted a screenshot below and the URL is: https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture/MVC_architecture

The previous page (https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture) works perfectly fine, just not this one.

![capture](https://user-images.githubusercontent.com/26879288/53688230-c1192d80-3d0e-11e9-89e6-9e0afa9f3acd.PNG)

**Comment by chrisdavidmills** [comment]
Hi there,

The content has been deleted because it is seriouasly out of date and noone has any time to update it. See https://emberjs.com/ for updated Ember documentation. Useful general information about MVC has been moved to https://developer.mozilla.org/en-US/docs/Glossary/MVC.

The parent page (https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture) was supposed to have been deleted as well, but there is a bug on the site stopping me from deleting it. Should be fixed soon. I'm sorry you wasted your time with this page.

**Comment by odsantos** [comment]
Hi @chrisdavidmills, just to remind that link is still showing the 404 error.
Thanks.
